### ISSUE TITLE
Composer support?

### ISSUE THREAD

**Issue by caseyw** [TSheetsTeam/api_phplib#4]
Hey there,

Is there anything stopping us from submitting a PR to add composer support?

It'd make adding into pre-existing projects quite a bit nicer.

Thank ya!

**Comment by dustinsweet** [comment]
Not at all Casey!  We think it would be really nice to have.  Please feel free to submit a PR and we will work with you to review and get it merged int.

**Comment by Benjaminhu** [comment]
> Not at all Casey! We think it would be really nice to have. Please feel free to submit a PR and we will work with you to review and get it merged int.

Hi, Pull request: [Composer support: composer.json #5](https://github.com/TSheetsTeam/api_phplib/pull/5) submitted!

**Comment by Benjaminhu** [comment]
@dustinsweet ping

**Comment by Benjaminhu** [comment]
@tsheets There is someone who maintains this repository?

**Comment by Benjaminhu** [comment]
@scottjeide There is someone who maintains this repository?

**Comment by scottjeide** [comment]
Sorry about that @Benjaminhu - I completely missed this PR! I'll take a look.

**Comment by Benjaminhu** [comment]
@scottjeide No problem, thanks!

**Comment by Benjaminhu** [comment]
@scottjeide Please release a version 1.0 from the package to work well. I sent it to the [packagist.org](https://packagist.org/packages/tsheetsteam/api_phplib) list, but I still get an error:

```
$ composer require tsheetsteam/api_phplib
                                                                                                                                                    
[InvalidArgumentException]                                                                                                                         
Could not find a version of package tsheetsteam/api_phplib matching your minimum-stability (stable). Require it with an explicit version constraint allowing its desired stability.    
```

Thanks.

**Comment by scottjeide** [comment]
I created the 1.0 tagged release. Is it working for you now @Benjaminhu ?

**Comment by Benjaminhu** [comment]
@scottjeide Thanks, it works!

```
$ composer require tsheetsteam/api_phplib
Using version ^1.0 for tsheetsteam/api_phplib
./composer.json has been updated
Running composer update tsheetsteam/api_phplib
Loading composer repositories with package information
Updating dependencies
Lock file operations: 1 install, 0 updates, 0 removals
  - Locking tsheetsteam/api_phplib (1.0)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing tsheetsteam/api_phplib (1.0): Extracting archive
Generating autoload files
```

**Comment by Benjaminhu** [comment]
@scottjeide I think it's done, works well, closeable, thank you!
